### ISSUE TITLE
[1.16.5] Cannot put items inside a Crude Storage Crate

### ISSUE THREAD

**Issue by ThousandFields** [Andromander/Gaia-Dimension#100]
**Versions:**
 - Minecraft: 1.16.5
 - Forge: 36.0.43
 - Gaia Dimension: 1.3.3

**To Reproduce:**
Attempt to put any items into a Crude Storage Crate using the cursor or shift click.

**Describe the bug**
Any and all items will be refused to be put inside the Crate.

**Additional context**
This is likely relatable with #99 , as both are crates and the Mega one references something about a blacklist in its crashlog. The difference is that attempting to put something in a Crude Storage Crate will not crash.

**Comment by Andromander** [comment]
Should be fixed in a164288
