### ISSUE TITLE
[1.16.5] Picking up Gaia fluid using an Iron Bucket transforms it into a Scanyx one, and vice versa

### ISSUE THREAD

**Issue by ThousandFields** [Andromander/Gaia-Dimension#101]
**Versions:**
 - Minecraft: 1.16.5
 - Forge: 36.0.43
 - Gaia Dimension: 1.3.3

**To Reproduce:**
Holding an Iron Bucket, right click Gaia Dimension fluids (Liquid Aura, Superhot Magma) to pick them up, OR
Holding a Scaynyx Bucket, right click non-Gaia fluids (Water, Lava) to pick them up

**Describe the bug**
The Iron Bucket, when used to pick up Gaia fluids, turns the bucket into a Scaynyx one. For example, using an Iron Bucket to pick up Liquid Aura will give the player a Liquid Aura Scaynyx Bucket. The opposite will happen with a Scanyx Bucket, and will transform to an Iron Bucket when used to pick up Water for example.

**Comment by Andromander** [comment]
Leaning on making this a feature.

That being said, I can look at preventing Scaynyx Buckets from picking up vanilla fluids, but I can't really fix Buckets picking up Gaia fluids, as that is handled in places I can't touch without hacks.

**Comment by Andromander** [comment]
Bucket to Scaynyx Bucket will be kept as a feature with the possibility of a recipe to turn a Scaynyx Bucket into a Bucket. However, I have prevented Scaynyx Buckets from turning into Buckets.
