### ISSUE TITLE
Client Crash While Loading Up Minecraft?

### ISSUE THREAD

**Issue by Yourname942** [Andromander/Gaia-Dimension#106]
**Versions ("Latest" is NOT a version):**
 - Minecraft: [e.g. 1.16.4] (required) 1.16.5
 - Forge: [e.g. 35.1.0] (required) 36.1.2
 - Gaia Dimension: [e.g. 1.3.0] (required) 1.16.5-1.3.2

**Crash Report**
(Attach via [Gist](https://gist.github.com/). This is required. Failure to do so will result in immediate closure of the issue)
crash log:
https://gist.github.com/Yourname942/6dcf811cf13935397f78edef65277f88

latest log:
https://gist.github.com/Yourname942/195867ceb7879b15e29f34ef7998834c

**To Reproduce:**
Steps to reproduce the behaviour. This is required for easier diagnosis:
1. create a preset with terraforged mod (follow this guide) https://github.com/TerraForged/community/wiki/Forge-Server
2. make sure to set up the server properties correctly.
3. launch the server
4. launch the client 
5. client crash while loading (never got to the main menu)

**Additional context**
(Include any details that could not fit into any of the categories above. This may include other mod information, links to issues on other repositories for cross-referencing, and any other note that may be important. This section is optional.)

**Comment by Andromander** [comment]
Is this issue consistent or random? I have this mod working just fine on servers, and this sort of error shouldn't even be happening. Need to see if this is some form of conflict or odd behaviour.

**Comment by Andromander** [comment]
Upon inspection, it appears this bug may have already been resolved in dev during a code cleanup. I'll consider this resolved in dev.
