### ISSUE TITLE
Mod causes crash do to issue with Pyrite_torch

### ISSUE THREAD

**Issue by judicius** [Andromander/Gaia-Dimension#108]
**Versions ("Latest" is NOT a version):**
 - Minecraft: 1.16.5
 - Forge: [e.g. 36.1.23
 - Gaia Dimension: 1.3.3

**Crash Report**
https://gist.github.com/judicius/2c992b753d668f5d2212db72e76be154

**To Reproduce:**
Upgraded to new Gaia Dimension with ceiling torch installed.

**Additional context**
(Include any details that could not fit into any of the categories above. This may include other mod information, links to issues on other repositories for cross-referencing, and any other note that may be important. This section is optional.)

**Comment by Tamaized** [comment]
Issue is on Ceiling Torch's end.
Specifically this line: https://github.com/bl4ckscor3/CeilingTorch/blob/5370f72b6b20218efcc5e05934a89ffbda5784d9/src/main/java/bl4ckscor3/mod/ceilingtorch/compat/gaiadimension/GaiaDimensionCompat.java#L30

Can report it here: https://github.com/bl4ckscor3/CeilingTorch/issues

**Comment by Bidgam** [comment]
Confirmed here as well.

**Comment by Andromander** [comment]
The issue appears to be caused by a registry change. Items used to be just an Item, but now that they are RegistryObjects, they need a little different treatment, which hasn't been done just yet.

I'll keep this open and watch it until it has been fixed.

**Comment by judicius** [comment]
Fixed with Ceiling Torch v1.11
