### ISSUE TITLE
List of possible suggestions

### ISSUE THREAD

**Issue by ZombieEnderman5** [Andromander/Gaia-Dimension#11]
Hello everyone, just thought I'd make a list of suggestions, based around the current build as of March 16th, 2018. List below:

1. The ability to craft the mod's planks into a crafting table.
2. The ability to craft the mod's planks into wooden tools.
3. Gaia Cobblestone, counterpart of Overworld cobblestone.
4. Making blocks return the correct metadata when mined - for example, Green Crystal Growths returning themselves when mined, not Pink Crystal Growths, which is what happens right now. Another example would be making Ouziums return themselves, not Thiscus, when mined.
5. Make the different types of grasses return Heavy Soil when mined, not themselves, which is what happens currently.
6. Please retexture the ores' backgrounds to match Gaia Stone, as they currently do not.
7. The Green Agate Jungle does not look like a jungle currently; rather, it looks like a slightly sparse forest. Please change this, either by making the trees generate more densely, or changing them to look more like Overworld jungle trees. The last choice is a matter of opinion; you can do it or not, I'm satisfied with either one.
8. Currently, vanilla animals and monsters spawn in the Gaia Dimension, is this intended? I feel like it's contrasting with the dimension, so please replace them with your own animals and monsters, even if just remakes of the vanilla ones.

That's all for now, hope you like it!
P.S. I'm asking this of Andromander, but others can comment. Why not share your ideas, too?

**Comment by Andromander** [comment]
I believe the latest release (untagged-1c7e65bc27a822a26b54) should have all these incorporated. If there are other suggestions, you can create a new issue, or reopen this issue with the new suggestions in the comments or the main comment edited.
