### ISSUE TITLE
Odd fluidlogging glitch with water plants

### ISSUE THREAD

**Issue by EvergreenSystems** [Andromander/Gaia-Dimension#110]
**Versions ("Latest" is NOT a version):**
 - Minecraft: [1.16.5] (required)
 - Forge: [35.1.0] (server and client) (required)
 - Gaia Dimension: [1.16.5-1.3.3-unofficial-4] (required)
 - Client log: n/a

**To Reproduce:**
Steps to reproduce the behaviour. This is required for easier diagnosis:
1. Place a water plant in sweet muck or any water-like liquid added by gaia (kelp, seagrass, etc)

**Describe the bug**
The plant in question does survive, but the fluid in the rest of that plants block is transformed into vanilla water without mixing, which looks quite odd. If the plant is destroyed the water is retained

**Screenshots**
![2021-05-25_16 10 37](https://user-images.githubusercontent.com/23658767/119569748-c8580600-bd74-11eb-8c48-876a3d86d138.png)
![2021-05-25_16 12 00](https://user-images.githubusercontent.com/23658767/119569750-c9893300-bd74-11eb-8743-45f978b03892.png)
![2021-05-25_16 12 03](https://user-images.githubusercontent.com/23658767/119569753-ca21c980-bd74-11eb-89ca-451a35cafdff.png)
![2021-05-25_16 16 39](https://user-images.githubusercontent.com/23658767/119569754-caba6000-bd74-11eb-9e56-6f85bbe59dbc.png)

**Additional context**
Discovered on the TF testing server

**Comment by Andromander** [comment]
Due to how waterlogging works, those plants can't be waterlogged with non-Water blocks (as in the Water block itself, not fluids with the properties of water). It's on vanilla to make waterlogging accept other fluids, or Forge if it is possible to patch that logic.
