### ISSUE TITLE
[Bug] Immense memory leak within the dimension.

### ISSUE THREAD

**Issue by wrachilles** [Andromander/Gaia-Dimension#113]
### Minecraft Version

1.15.2

### Forge Version

31.2.50

### Gaia Dimension Version

1.2.3

### To Reproduce

1. First step
2. Second step
3. Third and so on...more steps can be added

### Describe the Bug

So, first off, I know this is on 1.15.2, but it's kind of a problem for a modpack in particular, and I was mostly wondering if it could be looked into, or if it's an engine limitation with 1.15.2 vs 1.16. Of my friends playing the Craft to Exile: Dissonance pack, which is using the most up to date Gaia Dimension version for 1.15, there is an immense memory leak, to the tune of rendering my instance, running 12 gigs of ram, unplayable, within 20 to 30 minutes of entering the dimension, and my other friend just steadily gets worse over time. It only happens in the gaia dimension, and the pack creator is using the dimension for semi endgame of the pack, requiring much exploration which isn't really possible with how much of a memory leak there is. If there's any form of logs I can give that may be of aid, let me know. 

### Please read and confirm you have done the following

- [x] I have verified my report is unique and is not already opened or closed.
- [X] The versions listed above are accurate and not a vague answer (ie. "Latest", "I don't know") and all details provided are clear and concise.

**Comment by Andromander** [comment]
I would need some sort of profile for the performance, however, 1.15.2 is no longer a supported version and I'm very much unlikely to do updates on old versions.

**Comment by wrachilles** [comment]
Just a spark profile for that, or would you recommend something different? Also, that's understandable, but also disappointing (Hard to say that without sounding like a jerk, don't mean it that way.) For various reasons, the modpack is still in development for 1.15, and isn't updating to 1.16 iirc.

**Comment by Andromander** [comment]
> Hard to say that without sounding like a jerk, don't mean it that way

It's fine. The disparity of mods on different versions is a legitimate problem, just my schedule often doesn't allow for it.

A Spark profile should suffice. I'm curious to know if logging out and back into a world (single player) or restarting the server (multiplayer) alleviates the lag. If not, see what happens when the game is restarted. Might confirm a theory of mine.

**Comment by wrachilles** [comment]
For me at least, it seems to partially fix after restarting minecraft, but I have also noticed that it bogs down my entire system until I restart afterwards. With one of my friends, they gradually go from 200 fps in the dimension, down to eventually 1, then when they restart minecraft, it's all fine. So we have somewhat different experiences, but they also run optifine, and I do not, so, possible differences. 

I'll have a spark profile soon, I just need to sacrifice my PC to the gods of the gaia dimension for a while.

**Comment by wrachilles** [comment]
Also to add, the server does not lag one bit from the dimension, all the lag is purely client side.

**Comment by Andromander** [comment]
Yeah, so I think this ties to a theory of mine.

I had this mod tested on a 1.16 server and some server side lag was detected. After eventually delving into it, turns out it relates to how the sky rendering is done, namely it makes a new render of the sky every so often. The solution was just to make it check if there was no sky render and then apply it if that's the case.

It should be a small fix on my end, and I may also be able to publish it since I have the version number available. If the pack dev is still actively maintaining the mod, may also be worth poking them when I do release it.

**Comment by wrachilles** [comment]
That honestly sounds like it'd be the culprit, because we went into the advanced F3 menu, and going  through the highest items in the list was the gaia sky, so it is most likely that indeed, just waiting on my server to satrt back up for the profile though, so you can know for sure. If you wouldn't mind fixing that, it'd make things leaps and bounds easier for everyone doing this pack, and yes, the pack is indeed still being maintained.

**Comment by wrachilles** [comment]
Alright, technical difficulties are preventing me from getting the spark profile, and I really do need to get to bed, I was pushing it going for this profile, but I figured it was an alright cause, but the things barring me from doing so right now require more troubleshooting than my addled mind can handle. I'll get it to you as soon as I can, sorry.

**Comment by Andromander** [comment]
It's all good. Currently trying to get the workspace to function, but things are going a bit awry for not really a good reason. May take a while for a build to be made.

**Comment by Andromander** [comment]
I've uploaded version 1.2.4 which should apply the fix to the leak.

**Comment by wrachilles** [comment]
I have let the creator know, thank you immensely!
