### ISSUE TITLE
Crash when killing Malachite Guard with commands

### ISSUE THREAD

**Issue by mxnmnm** [Andromander/Gaia-Dimension#120]
**Versions ("Latest" is NOT a version):**
 - Minecraft: 1.16.5
 - Forge: 36.2.39
 - Gaia Dimension: 1.3.3
 - Client log: https://gist.github.com/mxnmnm/ce98b008be7d209aaea7005839a113f1

**To Reproduce:**
Steps to reproduce the behaviour. This is required for easier diagnosis:
1. Spawn malachite guard 
2. Do /kill @e[type=!player]
3. Crash

**Comment by Andromander** [comment]
I've attempted to reproduce this in 1.19.4, but I haven't stumbled across it.

There have been a few changes to how the Drones and Guards are handled, so it might be while I was porting, I had fixed the issue. Come to think of it, I may have fixed it in f51784daf71b2eb47c9973785c5c77def4bd060a.
