### ISSUE TITLE
[Crash] 

### ISSUE THREAD

**Issue by Vylidan** [Andromander/Gaia-Dimension#122]
### Minecraft Version

1.19.4

### Forge Version

45.0.64

### Gaia Dimension Version

1.19.4-2.0-79

### Crash Log

<script src="https://gist.github.com/Vylidan/413c90800cea388f59564c5734650340.js"></script>

### To Reproduce

1. Build Agate Crafting table
2. right click agate crafting table once placed in survival mode

### Please read and confirm you have done the following

- [X] I have verified my report is unique and is not already opened or closed.
- [X] The versions listed above are accurate and not a vague answer (ie. "Latest", "I don't know"), a valid link to the crash report, and all details provided are clear and concise.

**Comment by Andromander** [comment]
I've applied what I think should be a bandaid fix for now. Hunch was correct in where the issue was coming from. Feel free to reopen if it persists.

Ideally, I should add a Recipe Book button to the table. Whether I do that just depends on how I feel or enough people ask me.
