### ISSUE TITLE
[Bug] 1.19.4 portal creation preserves the y-level of the overworld portal

### ISSUE THREAD

**Issue by EvergreenSystems** [Andromander/Gaia-Dimension#123]
### Minecraft Version

1.19.4

### Forge Version

45.0.59

### Gaia Dimension Version

1.3.3

### To Reproduce

1. Light a portal at a high y-level in the overworld
2. Enter the portal

### Describe the Bug

Instead of placing the gaia-side of the portal at ground level, it preserves the y-level of the overworld portal (potentially leading to a portal stuck way up in the sky).

### Additional Details

![2023-05-19_12 04 05](https://github.com/Andromander/Gaia-Dimension/assets/23658767/2227abe6-aa98-4168-842f-f4584c5c9dda)
![2023-05-19_12 03 19](https://github.com/Andromander/Gaia-Dimension/assets/23658767/5a7ae5f9-b436-4f02-9221-25c0d6090f4b)

### Please read and confirm you have done the following

- [X] I have verified my report is unique and is not already opened or closed.
- [X] The versions listed above are accurate and not a vague answer (ie. "Latest", "I don't know") and all details provided are clear and concise.

**Comment by Andromander** [comment]
I did *something* to the portal logic just now because it turns out it wasn't actually working. From what I can tell it works now, but it'd need more testing than just the one round trip.
