### ISSUE TITLE
[Bug] 1.19.4 Sounds associated with mineral water missing

### ISSUE THREAD

**Issue by EvergreenSystems** [Andromander/Gaia-Dimension#125]
### Minecraft Version

1.19.4

### Forge Version

45.0.59

### Gaia Dimension Version

1.3.3

### To Reproduce

1. Do things in mineral water that would normally generate a sound with vanilla water (jump in, pick up in a bucket, etc)

### Describe the Bug

All sounds associated with normal fluid behavior are missing (except for, oddly enough, placing from a bucket). As the sound is seemingly missing, subtitles are not generated either.

### Please read and confirm you have done the following

- [X] I have verified my report is unique and is not already opened or closed.
- [X] The versions listed above are accurate and not a vague answer (ie. "Latest", "I don't know") and all details provided are clear and concise.

**Comment by EvergreenSystems** [comment]
Appears to propagate across all fluids that Gaia adds

**Comment by Andromander** [comment]
Can confirm the missing bucket sounds (and in some cases, vapourising) is a result of some missing FluidType Properties.

However, there may be some sounds that I simply cannot control. For example, controlling water splash effects such as sounds and particles are out of my control. Forge recently changed how fluids are handled, but only partially; a modded fluid does not set or check `wasTouchingWater` but with a different method, but there are places where only this field is checked. One such place just so happens to be splashing sounds.
Long short of it: upstream issue.

**Comment by Andromander** [comment]
I've added the bucket empty, bucket fill, and fluid vaporise sounds, which is currently all I can do on my end. Feel free to list any and all actions without an associated sound in this issue, I'll reopen if there's something I can fix.

Currently, jumping into water does not have the option to add sounds.
