### ISSUE TITLE
[1.20.1] Mineral Water source blocks cannot be replaced with a block

### ISSUE THREAD

**Issue by EvergreenSystems** [Andromander/Gaia-Dimension#132]
**Versions ("Latest" is NOT a version):**
 - Minecraft: 1.20.1
 - Forge: 47.0.13
 - Gaia Dimension: 2.1.92

**To Reproduce:**
Steps to reproduce the behavior. This is required for easier diagnosis:
1. Attempt to replace a mineral water source block with another block (any block)

**Describe the bug**
While one would expect to simply place the block down, replacing the fluid, in actuality it is impossible to place the block down.

**Screenshots**

**Additional context**

**Comment by Andromander** [comment]
"This commit closes issue 132" my ass.

**Comment by Tamaized** [comment]
It's because your main branch is 1.19
