### ISSUE TITLE
Retexture Overhaul, Reduxed

### ISSUE THREAD

**Issue by Andromander** [Andromander/Gaia-Dimension#18]
Tracking Issue.

Some textures were made in a rush, while others were made with limited equipment. The following are ones I deem necessary. Any other asset may be altered too, but may be rejected.

### ITEMS
- [x]  Malachite Armor Pieces
- [x]  Tiger's Eye Armor Pieces
- [ ]  Spinel Armor Pieces
- [x]  Zircon Armor Pieces
- [x]  Corrupted Armor Pieces
- [ ]  Bixbite Armor Pieces
- [x]  Tsvarovite Head Piece
- [ ]  Larvikite Armor Pieces
- [ ]  Gaia Armor Pieces
- [x]  Goldstone
- [ ]  Lurmorus Meat
- [ ]  Lurmorus Steak

### ARMOUR
- [x]  Malachite
- [x]  Tiger's Eye (Minor)
- [x]  Spinel
- [x]  Zircon
- [x]  Corrupted (Must match Gaia, small alterations)
- [x]  Bixbite (Minor)
- [x]  Tsvarovite (Minor)
- [x]  Larvikite (Minor)
- [x]  Gaia (Must match Corrupted, small alterations)

### BLOCKS (Note: CTM can be used here)
- [x]  All Agate Logs
- [x]  Cinnabar Block
- [x]  Benitoite Block
- [x]  Gaia Stone
- [x]  Gaia Cobblestone
- [x] Glitter Grass (aka. How to get a good texture via block tinting)

### ENTITIES
- [x]  All small Growth Sappers
- [x]  Howlite Wolf (Note: May be remodelled)
- [x]  Malachite Guard (Note: May be remodelled)
- [x]  Shalurker
- [x]  Agate Golem (Minor)

### GUI
- [x]  Gaia Stone Furnace
- [x]  Restructurer
- [x]  Purifier

**Comment by OceanusProcellarum** [comment]
Alright here's something that I can help with. I could start with armour pieces. Are there any particular criteria or visions you have for what they would look like? Or can I take a bit of artistic freedom?

**Comment by Andromander** [comment]
The already existing armour has the basic shape I am after. My problem with these is that they looked like it was slapped together (and they were), and the items in the inventory mostly look like what they appear to be on the player, but are a bit rushed. The Champion and Corrupt armor sets are meant to look similar to each other. 

Some of these also have tooltips to roughly describe their properties or appearance. 

I've stuck to the vanilla armour model, so they don't have any protrusions, but if possible, I could accomodate for fancy models.

**Comment by OceanusProcellarum** [comment]
I'll probably remodel some of the armor since there's only so much you can do with the vanilla model. In the meantime, I'll probably texture and retexture a few swords. What exactly are you going for with the Gaia Champion Sword? Also here's my version of the Zircon Prince Razor (it could be animated with electricity in between the prongs).
![zircon_prince_razor]
(https://user-images.githubusercontent.com/41199523/42795205-a4c94e92-89b5-11e8-949d-b185fbb451ac.png)

**Comment by Andromander** [comment]
That is a nice Zircon Prince Razor. 

As for the Gaia Champion Sword, I guess I was after an elegant approach, but didn't exactly work out as planned. Suppose that it is a tough crystalline blade with the handle decorated with rare stones (akin to the decorations on the side of the already existing armor set).

As a side note, the Corrupt Warrior Sword has a similar design to the Gaia Champion Sword, but with silver, very dark blue, orange and dark grey colours and a minor difference in shape.

**Comment by Andromander** [comment]
Due to time constraints, I will be closing this as "complete".
