### ISSUE TITLE
Give textures to those missing them

### ISSUE THREAD

**Issue by Andromander** [Andromander/Gaia-Dimension#19]
Tracking Issue.

I have pushed for some tools, but they do not have any textures, let alone a model json.

- [x]  Tiger's Eye Mace
- [x]  Spinel Princess Flamberge
- [x]  Corrupt Warrior Sword
- [x]  Gaia Duchess Khopesh
- [x]  Gaia Baron Dagger
- [x]  Gaia Duke Blade
- [x] Carnelian Tools
- [x] Benitoite Tools
- [x] Chalcedony Tools
- [x] Sugilite Armor
- [x] Proustite Armor
- [x] Leucite Armor
- [x] Carnelian Armor
- [x] Chalcedony Armor

**Comment by OceanusProcellarum** [comment]
So is it Apex Predator or Tiger's Eye? It appears to me that the two names refer to the same thing

**Comment by Andromander** [comment]
Yeah, they're the same thing. Apex Predator refers to the name of the boss, while Tiger's Eye refers to the gemstone it is based on.

**Comment by OceanusProcellarum** [comment]
For the remaining 3, the Dutchess, Baron, and Duke weapons, have you come up with color schemes yet? If not then I'll see what I can do. I have a plan for the designs already, based on the in-game descriptions and names, but perhaps you have suggestions on how to design them?

**Comment by Andromander** [comment]
Duchess is based on Bixbite (so a hot pink colour), and is more on an Egyptian feel, since the weapon is a Khopesh. I also plan on it being able to be thrown in a similar fashion to a boomerang, which would go with the concept on the boss (floating and able to split parts around). 

Baron is based on Tsvarovite (so a general green colour) , and is a small dagger. The overall theme is both well-dressed (considering the armour) but there's also a hidden Viking theme I'd like to incorporate. It is just a dagger though, and it can pierce armour. 

The Duke is based on Larvikite (a dark but also somewhat reflective silver flecks). It's slightly sci-fi in appearance, so some highlights on the design could be interesting. The blade would be more for slicing down, unlike a double-edged sword, so one end is sharp, but the other is blunt.

**Comment by Andromander** [comment]
All textures complete, closing.
