### ISSUE TITLE
Incorrect Bucket Recipe

### ISSUE THREAD

**Issue by WenXin20** [Andromander/Gaia-Dimension#38]
Gaia Dimension v1.0.2

I assume that the bucket recipe is incorrect since it doesn't seem to have a way to craft it, while the ingot has this weird recipe:
![2019-03-23_11 08 36](https://user-images.githubusercontent.com/12000593/54869345-1c19cf80-4d65-11e9-9eb2-192a36274680.png)

**Comment by Andromander** [comment]
This is probably why I shouldn't do things late at night.
Anyway, good catch. I've released a new version with a hotfix for this issue.
