### ISSUE TITLE
Mechanic - Armor Weight

### ISSUE THREAD

**Issue by Andromander** [Andromander/Gaia-Dimension#4]
For stronger armor (excluding Gaia Champion), add weight to them. There is a threshold of how much weight can be applied to a player before negative effects are applied, such as Slowness, Weakness, and more.
This will come in handy to balance out overpowered sets and create a small strategy system in how a player can utilise sets.
* Sets below the threshold are typically weaker
* Sets on the threshold are standard
* Sets beyond the threshold are stronger

Perhaps add a special enchanting system that can add weight to armor, but also adds new skills?

**Comment by ZombieEnderman5** [comment]
Souns great! :+1: (You know me in Discord as DeadlyBlueApples)

**Comment by Andromander** [comment]
Ultimately, I might not do this. I could bring this back in a different form, but for now, this isn't the main focus. Will close for the time being, or permanently if I decide to not do this, or recreate as something else, but similar.

This will not, however, prevent the Corrupt Warrior Armour from receiving a similar trait to this.
