### ISSUE TITLE
Config to disable portal needing hot biomes

### ISSUE THREAD

**Issue by ghost** [Andromander/Gaia-Dimension#61]
Hi, so im making a skyblock modpack and chances are the player wont spawn in a required biome to open the portal

your main curseforge page says this can be disabled, but its missing from the 1.14 config file

Forge: 28.2.1
Gaia: 1.14.4 - 1.1.2

**Comment by Andromander** [comment]
If I recall, the option is in the Server config, meaning it is stored per world. To change it, you'll need to go to the world's save folder, find the "serverconfig" folder, and then the file for Gaia Dimension.
If you want all save files created to have this option changed, you can copy the config from the world into a folder called "defaultconfig" in the game's files. Note this only applies to newly-created worlds.

**Comment by ghost** [comment]
oh, didnt realise worlds have config files too now,

thanks a lot
