### ISSUE TITLE
Unable to connect to server

### ISSUE THREAD

**Issue by MrGuitou** [Andromander/Gaia-Dimension#73]
- Minecraft: 1.16.4
 - Forge: 35.1.7
 - Gaia Dimension: 1.3.0

**Crash Report**
none - game does not crash, there's just an error when connecting to server, resulting an immediate disconnect

**To Reproduce:**
1. Run a modded server with Gaia Dimension
2. Try to connect with client
3. get the crash

**Additional context**
Server run many other mods, some of them adding new biomes and dimensions, like Biomes'O'Plenty, World Blender, Advance Mining Dimension.

I saw there's seem to get some conflict with BOP on an other issue, but mine don't seem to be strictly the same, so I don't if it is related or not... 

I tested everything in solo, and everything goes well, without any bug, and I didn't seen any conflict with biomes nor dimension mods, every mods working well together (by the way, Gaia Dimension is really cool)

But when trying to connect on a fresh generated world on a LAN server, it cause this error:

`09:24:03.945
net.minecraft.world.biome.BiomeGenerationSettings
Netty Client IO #1
Feature: Not a JSON object: "gaiadimension:roofed_agaric"; Not a JSON object: "gaiadimension:crystal_blooms_common"; Not a JSON object: "gaiadimension:crystal_growth_04"; Not a JSON object: "gaiadimension:green_agate_tree"`

This also give an error on game client:
![image](https://user-images.githubusercontent.com/63423311/101275711-0f8f1200-37a8-11eb-9c35-1c465ea012bf.png)

No error displayed server-side (have searched in log and debug, nothing related except client connect/disconnect line)

Therefore, an error on launch may be related.
WorldBlender seem have few trouble about Gaia Dimension:

`[06déc.2020 09:09:43.963] [main/ERROR] [world_blender/]: 
****************** World Blender ******************

 Found some unregistered ConfiguredFeatures, ConfiguredStructures, and/or
 ConfiguredCarvers. These unregistered stuff will not spawn in WorldBlender's dimension
 as unregistered stuff can wipe out everyone else's registered stuff from biomes.
 The creators of those mods need to register their stuff.
 Here are the following that will not show up in WB's dimension: 

gaiadimension:agathum
gaiadimension:aura_leaves
gaiadimension:aura_log
gaiadimension:aura_sapling
gaiadimension:aura_shoot
gaiadimension:aura_tree
gaiadimension:bismuth_geyser
gaiadimension:bismuth_spire
gaiadimension:blue_agate_leaves
gaiadimension:blue_agate_log
gaiadimension:blue_agate_sapling
gaiadimension:blue_agate_tree
gaiadimension:bog_patch
gaiadimension:boggy_soil
gaiadimension:bulbous_hobina
gaiadimension:burning_leaves
gaiadimension:burning_log
gaiadimension:burning_sapling
gaiadimension:burnt_agate_tree
gaiadimension:burnt_leaves
gaiadimension:burnt_log
gaiadimension:burnt_sapling
gaiadimension:chasms
gaiadimension:cinnabar_ore
gaiadimension:coarse_rock
gaiadimension:corrupt_grass
gaiadimension:corrupt_soil
gaiadimension:corrupted_gaia_eye
gaiadimension:corrupted_leaves
gaiadimension:corrupted_log
gaiadimension:corrupted_sapling
gaiadimension:corrupted_varloom
gaiadimension:crystal_caves
gaiadimension:crystal_growth
gaiadimension:crystal_growth_aura
gaiadimension:crystal_growth_black
gaiadimension:crystal_growth_mutant
gaiadimension:crystal_growth_red
gaiadimension:crystal_growth_seared
gaiadimension:elder_imklia
gaiadimension:fiery_agate_tree
gaiadimension:fossilized_leaves
gaiadimension:fossilized_log
gaiadimension:fossilized_sapling
gaiadimension:fossilized_tree
gaiadimension:frail_blob
gaiadimension:gaia_blob
gaiadimension:gaia_disk
gaiadimension:glitter_grass
gaiadimension:gold_orb_tucher
gaiadimension:goldstone_tree
gaiadimension:green_agate_leaves
gaiadimension:green_agate_log
gaiadimension:green_agate_sapling
gaiadimension:green_agate_tree
gaiadimension:gummy_glitter_block
gaiadimension:heavy_soil
gaiadimension:hematite_ore
gaiadimension:impure_sludge
gaiadimension:labradorite_ore
gaiadimension:light_soil
gaiadimension:liquid_aura
gaiadimension:liquid_bismuth
gaiadimension:malachite_watchtower
gaiadimension:mineral_water
gaiadimension:mini_tower
gaiadimension:moonstone_ore
gaiadimension:murky_grass
gaiadimension:mystical_murgni
gaiadimension:opal_ore_blue
gaiadimension:opal_ore_green
gaiadimension:opal_ore_red
gaiadimension:opal_ore_white
gaiadimension:ouzium
gaiadimension:pebbles
gaiadimension:pink_agate_leaves
gaiadimension:pink_agate_log
gaiadimension:pink_agate_sapling
gaiadimension:pink_agate_tree
gaiadimension:pool
gaiadimension:precious_rock
gaiadimension:primal_mass
gaiadimension:purple_agate_leaves
gaiadimension:purple_agate_log
gaiadimension:purple_agate_sapling
gaiadimension:purple_agate_tree
gaiadimension:pyrite_ore
gaiadimension:raw_amethyst
gaiadimension:raw_copal
gaiadimension:raw_jade
gaiadimension:raw_jet
gaiadimension:roofed_agaric
gaiadimension:salt
gaiadimension:searing_rock
gaiadimension:soft_grass
gaiadimension:speckled_rock
gaiadimension:spotted_kersei
gaiadimension:static_spike
gaiadimension:static_stone
gaiadimension:stickly_cupsir
gaiadimension:sugilite_ore
gaiadimension:superhot_magma
gaiadimension:sweet_muck
gaiadimension:thick_glitter_block
gaiadimension:thiscus
gaiadimension:thorny_wiltha
gaiadimension:wasteland_stone`

Keep up the good job.
Regards.

**Comment by Andromander** [comment]
I think for this sort of error, I may need the full client log, as the issue itself mentions "mobData". It might have some more information, as well as a mod list.
What I might also be interested is if an error occurs with Gaia Dimension alone when creating a LAN server. If so, I may be able to isolate down the bug.

**Comment by MrGuitou** [comment]
Here's client log:
[client.log](https://github.com/Andromander/Gaia-Dimension/files/5648586/client.log)

Here's server logs:
[server.log](https://github.com/Andromander/Gaia-Dimension/files/5648591/server.log)
And the debug file that come alongside:
[debug.log](https://github.com/Andromander/Gaia-Dimension/files/5648592/debug.log)

Hope this should help you.

**Comment by Andromander** [comment]
Checking the debug log, I found reference to this "mobData" and took a look at Caged Mobs to see whether it has something similar. It appears to have been reported [here](https://github.com/Corgam/CagedMobs/issues/13) already, so it might be worth having a check here, too. That being said, there is very little information about the error itself except for the screenshot even with all the logs here, so the cause itself could be a mystery.

As for the configured feature issue, can you make a separate Bug Report for that? It will be worth having a closer look at that.

**Comment by Corgam** [comment]
I'm the creator of the Caged Mobs mod. It was a bug from my mod, but it should be fixed in the newest version. I think the crash has nothing to do with Gaia Dimension mod.

**Comment by MrGuitou** [comment]
Ok, So....

After update Caged Mobs, I succesfully connect \o/

Thanks a lot to @Andromander and @Corgam  for support 👍 

Keep up the good job, you two.

Best regards.
