### ISSUE TITLE
Not a JSON object

### ISSUE THREAD

**Issue by judicius** [Andromander/Gaia-Dimension#76]
**Versions ("Latest" is NOT a version):**
 - Minecraft: [1.16.4
 - Forge: [35.1.13
 - Gaia Dimension:  1.3.0]
 - Client log

**To Reproduce:**
Steps to reproduce the behaviour. This is required for easier diagnosis:
Server Starutp

**Describe the bug**
Console reporting

17.12 09:32:47 [Server] main/ERROR Feature: Not a JSON object: "gaiadimension:roofed_agaric"; Not a JSON object: "gaiadimension:crystal_blooms_common"; Not a JSON object: "gaiadimension:crystal_growth_04"; Not a JSON object: "gaiadimension:green_agate_tree"

**Screenshots**
(For bugs that have a visual glitch. If this bug does not have a visual issue or cannot be conveyed through a screenshot, delete this section. Video evidence may be used here, too.)

**Additional context**
(Include any details that could not fit into any of the categories above. This may include other mod information, links to issues on other repositories for cross-referencing, and any other note that may be important. This section is optional.)

**Comment by Andromander** [comment]
I wish I knew why this happens and how to fix it. I havr made attempts to mitigate the issue locally,  but there isn't a way to stop it.

**Comment by Andromander** [comment]
Just as a note to self: the bushes feature in the Green Agate Jungle is a fault for some reason. The feature itself doesn't spit an error, but attempting to add the feature causes every other feature to have an issue.

The solution I'm thinking of implementing may cause worldgen changes.
