### ISSUE TITLE
Use forge tags for items to improve cross-mod compat

### ISSUE THREAD

**Issue by Syndaryl** [Andromander/Gaia-Dimension#89]
**Describe the feature you would like to see**
I would like the gaia-dimension materials to be tagged/ore-dictd using the forge tag system, allowing equivalent materials from other mods to be used in the place of gaia-dimension materials, and vice versa.
I can see some of the items are tagged, but the gem dusts aren't yet, nor the logs, leaves, possibly other items although those were the ones that I spotted. I would also suggest adding gaia stone/cobblestone to the stone and cobblestone tags, so that players in the gaia dimension can access some basic crafting recipes.

**Why do you think this feature should be in the mod?**
Cross-mod compatibility is highly desirable - it makes it much easier to integrate a mod into a mod pack, particularly for end-user home-rolled mod packs. It means there's some out-of-the-box compat without using crafttweaker scripts or rolling your own data packs, which the average user doesn't do.

**Comment by Andromander** [comment]
For now, I'm leaving the Dusts untagged as they are on feature limbo; I may remove them or keep them depending on whether I can get to use them.

I've added various new Tags in a past commit, so this should be dealt with for now. If there are any more that needed to be added, make sure to open a new commit with a specified list.
