### ISSUE TITLE
Minecraft: 1.16.5

### ISSUE THREAD

**Issue by ParmesanGoldfish** [Andromander/Gaia-Dimension#91]
Versions:
 - Minecraft: 1.16.5
 - Forge: 36.0.42
 - Gaia Dimension: 1.3.2

To Reproduce:
1. Enter Gaia Dimension portal.
2. That's it.

Description
Screen tearing while in the Gaia dimension, sky is black. Changing render distance does not seem to do anything. Changing between windowed and fullscreen modes does help.

Screenshots:
![Screen-tear](https://user-images.githubusercontent.com/79711185/109323633-aa384380-7821-11eb-9c9d-f1ad2ad7dea1.png)
![Screen-tear-2](https://user-images.githubusercontent.com/79711185/109323640-ad333400-7821-11eb-9e60-16ef4b92aae7.png)
![Dark-sky](https://user-images.githubusercontent.com/79711185/109323650-b0c6bb00-7821-11eb-8d6b-04add1903579.png)

Additional Information:
Running Minecraft on macOS Big Sur 11.2.1. Playing on a small multiplayer server with several other mods loaded. Other players are not experiencing these issues.

**Comment by Andromander** [comment]
I have a hunch that Optifine is installed, would this be right?

**Comment by Andromander** [comment]
Looking at the screenshots closely, this may likely be an issue with the shaders, which may then be a problem caused by Optifine. Unfortunately, there is nothing I can do as the source for Optifine is closed and thus cannot tell what is happening.
