### ISSUE TITLE
[1.16.5] Gaia Dimension gem blocks are not available as Beacon base or payment item

### ISSUE THREAD

**Issue by ThousandFields** [Andromander/Gaia-Dimension#92]
- Minecraft: 1.16.5
 - Forge: 36.0.43
 - Gaia Dimension: 1.3.2

When attempting to use any Gaia Dimension blocks labelled with "forge:beacon_payment" such as Sugilite, Tektite, or Goldstone, the Beacon will not activate. The same blocks in their uncompressed (gem) form also cannot be put in the payment slot to power a Beacon. This seems unintentional, as Gaia's gem blocks are very similar to vanilla's compressed resource blocks, and also because they are labelled with "forge:beacon_payment".

![image](https://user-images.githubusercontent.com/58322110/110227155-4cf85e00-7ec3-11eb-8f2a-0c381f5954d4.png)

I did however notice that vanilla's resources that are available for Beacon bases or payment are labelled with "minecraft:beacon_payment_items" instead of Gaia's "forge:beacon_payment". As this was noticed on the official TF server, other mods such as The Undergarden were present, and UG's ingots were labelled with "minecraft:beacon_payment_items" and do function properly like the vanilla resource blocks.

![image](https://user-images.githubusercontent.com/58322110/110227199-d0b24a80-7ec3-11eb-9e30-a24f2bb6cd70.png)

**Comment by Andromander** [comment]
Should be fixed in 857e0d4
