### ISSUE TITLE
Waterlogging in mineral water does not function

### ISSUE THREAD

**Issue by EvergreenSystems** [Andromander/Gaia-Dimension#94]
**Versions: 1.16.5-1.3.2**
 - Minecraft: 1.16.5
 - Forge: 36.0.43
 - Gaia Dimension: 1.3.2
 - Client log: n/a

**To Reproduce:**
Steps to reproduce the behavior. This is required for easier diagnosis:
1. Place any normally waterloggable thing in mineral water, ie stone slabs/stairs or lanterns

**Describe the bug**
Things that are normally able to be waterlogged with vanilla water are not waterloggable in mineral water. Functions similarly to how vanilla water used to work with the block just creating an air pocket in the spaces not covered by the block proper, ie a stair would have one-quarter of the block air and the rest the stair itself rather than water and the stair

**Screenshots**
![2021-03-14_21 22 28](https://user-images.githubusercontent.com/23658767/111095895-69704800-850c-11eb-886e-edce4ef90d33.png)

**Additional context**
Observed this behavior on the TF testing server so I apologize if it has already been discovered and fixed

**Comment by Andromander** [comment]
Unfortunately, due to how Waterlogging works, this isn't possible. This is due to it hard-checking against Water, and the Blockstate itself is a boolean, so it can only be or not be Waterlogged, rather than storing the fluid that it has or doesn't have.
