### ISSUE TITLE
Mineral water replaces superhot magma

### ISSUE THREAD

**Issue by EvergreenSystems** [Andromander/Gaia-Dimension#95]
**Versions ("Latest" is NOT a version):**
 - Minecraft: 1.16.5
 - Forge: 36.0.43
 - Gaia Dimension:  1.3.2
 - Client log: n/a
 - 
**To Reproduce:**
Steps to reproduce the behaviour. This is required for easier diagnosis:

1. Put down a bucket of water over a pool of superhot magma 

**Describe the bug**
The mineral water replaces the superhot magma as if it was air, creating a column of flowing mineral water.

**Screenshots**
![2021-03-15_17 09 46](https://user-images.githubusercontent.com/23658767/111228243-da1d7000-85b1-11eb-98b7-8d58b94576a2.png)
![2021-03-15_17 09 52](https://user-images.githubusercontent.com/23658767/111228244-dab60680-85b1-11eb-8029-175360c7c8c3.png)
![2021-03-15_17 09 54](https://user-images.githubusercontent.com/23658767/111228246-dab60680-85b1-11eb-9cb6-412ca7c13ff0.png)

**Additional context**
Discovered on the tf testing server

**Comment by EvergreenSystems** [comment]
Also occurs with vanilla water
![2021-03-15_17 21 15](https://user-images.githubusercontent.com/23658767/111228863-eeae3800-85b2-11eb-890e-a2548733fec1.png)

**Comment by Andromander** [comment]
I'm going to assume this has been fixed, at least to the best of my ability. There's more handling in places.
