### ISSUE TITLE
Red and green opal ore cannot be smelted

### ISSUE THREAD

**Issue by EvergreenSystems** [Andromander/Gaia-Dimension#96]
**Versions ("Latest" is NOT a version):**
 - Minecraft: 1.16.5
 - Forge: 36.0.43
 - Gaia Dimension: 1.3.2
 - Client log: n/a

**To Reproduce:**
Steps to reproduce the behaviour. This is required for easier diagnosis:

1. Put green or red opal ore in a furnace with fuel

**Describe the bug**
Red and green opal ore will not smelt at all, just clogs the furnace like putting dirt in the top slot. Blue and white opal ore still smelt as intended

**Screenshots**

**Additional context**
Discovered on the tf server

**Comment by Andromander** [comment]
Fixed in 81ed6e8
